services:
  isim:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./config/conf_docker.ini:/app/config/conf.ini
    restart: unless-stopped

  neo4j:
    image: neo4j:5.21.0
    environment:
      - NEO4J_AUTH=neo4j/supertestovaciheslo
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_isim_data:/data
      - ${DATA_PATH}:/tmp/dumps/neo4j.dump
    ports:
      - 7474:7474
      - 7687:7687
    depends_on:
      neo4j_load_data:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474/"]
      interval: 10s
      timeout: 2s
      retries: 10
    restart: unless-stopped

  neo4j_load_data:
    image: neo4j:5.21.0
    environment:
      - NEO4J_AUTH=neo4j/supertestovaciheslo
    volumes:
      - neo4j_isim_data:/data
      - ${DATA_PATH}:/tmp/dumps/neo4j.dump
    entrypoint:
      - sh
      - -c
      - neo4j-admin database load --from-path=/tmp/dumps --overwrite-destination=true neo4j && neo4j-admin database migrate neo4j --force-btree-indexes-to-range
volumes:
  neo4j_isim_data: