type Application {
  name: String!
  devices: [Device!]! @relationship(type: "RUNNING_ON", direction: OUT)
}

type Component {
  name: String!
  missions: [Mission!]! @relationship(type:  "SUPPORTS", direction: OUT)
  hosts: [Host!]! @relationship(type:  "PROVIDED_BY", direction: OUT)
  from_mission_dependencies: [MissionDependency!]! @relationship(type: "FROM", direction: IN)
  to_mission_dependencies: [MissionDependency!]! @relationship(type: "TO", direction: IN)
}

type Contact {
  name: String!
  subnets: [Subnet!]! @relationship(type: "HAS", direction: IN)
}

type CVE {
  CVE_id: String!
  access_complexity: String
  access_vector: String
  attack_complexity: String
  attack_vector: String
  authentication: String
  availability_impact_v2: String
  availability_impact_v3: String
  base_score_v2: Float
  base_score_v3: Float
  confidentiality_impact_v2: String
  confidentiality_impact_v3: String
  description: String!
  impact: [String]!
  integrity_impact_v2: String
  integrity_impact_v3: String
  obtain_all_privilege: Boolean
  obtain_other_privilege: Boolean
  obtain_user_privilege: Boolean
  patched: String
  privileges_required: String
  published_date: String!
  scope: String
  user_interaction: String
  vendor_description: String
  vulnerability: Vulnerability! @relationship(type:  "REFERS_TO", direction: IN)
}

type Device {
  name: String
  state: String
  power: String
  hardware_version: HardwareVersion @relationship(type: "HAS", direction: OUT)
  applications: [Application!]! @relationship(type: "RUNNING_ON", direction: IN)
}

type DomainName {
  domain_name: String!
  tag: [String]!
  ips: [IP!]! @relationship(type:  "RESOLVES_TO", direction: IN)
}

type HardwareVersion {
  manufacturer: String!
  model: String!
  devices: [Device!]! @relationship(type: "HAS", direction: IN)
}

type Host {
  hostname: String
  node: NodeObject @relationship(type:  "IS_A", direction: IN)
  software_versions: [SoftwareVersion!]! @relationship(type:  "ON", direction: IN)
  components: [Component!]! @relationship(type:  "PROVIDED_BY", direction: IN)
  network_services: [NetworkService!]! @relationship(type: "ON", direction: IN)
}

type IP {
  address: String!
  version: Int
  domain_names: [DomainName!]! @relationship(type:  "RESOLVES_TO", properties: "ResolvesTo", direction: OUT)
  uris: [URI!]! @relationship(type: "IDENTIFIES", direction: OUT)
  nodes: [NodeObject!]! @relationship(type:  "HAS_ASSIGNED", direction: IN)
  subnets: [Subnet!]! @relationship(type:  "PART_OF", direction: OUT)
}

type NetworkService {
  protocol: String
  port: Int
  tag: [String]
  service: String
  hosts: [Host!]! @relationship(type: "ON", properties: "NetworkServiceOn", direction: OUT)
  software_versions: [SoftwareVersion!]! @relationship(type: "PROVIDES", direction: OUT, queryDirection: DEFAULT_UNDIRECTED)
}

type NodeObject @node(labels: "Node") {
  ips: [IP!]! @relationship(type:  "HAS_ASSIGNED", direction: OUT)
  host: Host @relationship(type:  "IS_A", direction: OUT)
  is_dependent_on_nodes: [NodeObject!]! @relationship(type:  "IS_DEPENDENT_ON", direction: OUT)
  is_connected_to_nodes: [NodeObject!]! @relationship(type:  "IS_CONNECTED_TO", direction: OUT)
}

type OrganizationUnit {
  name: String!
  subnets: [Subnet!]! @relationship(type:  "PART_OF", direction: IN)
  physical_environments: [PhysicalEnvironment!]! @relationship(type: "TENANTS", direction: OUT)
}

type PhysicalEnvironment {
  location: String!
  org_units: [OrganizationUnit!]! @relationship(type: "TENANTS", direction: IN)
}

type SoftwareVersion {
  tag: [String]!
  version: String!
  hosts: [Host!]! @relationship(type: "ON", properties: "SoftwareOn", direction: OUT)
  network_services: [NetworkService!]! @relationship(type: "PROVIDES", direction: OUT, queryDirection: DEFAULT_UNDIRECTED)
  vulnerabilities: [Vulnerability!]! @relationship(type: "IN", direction: IN)
}

type Subnet {
  note: String
  range: String!
  org_units: [OrganizationUnit!]! @relationship(type:  "PART_OF", direction: OUT)
  contacts: [Contact!]! @relationship(type: "HAS", direction: OUT)
}

type Mission {
  criticality: Int!
  description: String!
  name: String!
  structure: String!
  components: [Component!]! @relationship(type:  "SUPPORTS", direction: IN)
}

type MissionDependency {
  from_components: [Component!]! @relationship(type: "FROM", direction: OUT)
  to_components: [Component!]! @relationship(type: "TO", direction: OUT)
}

type URI {
  identifier: String!
  ips: [IP!]! @relationship(type: "IDENTIFIES", direction: IN)
}

type Vulnerability {
  description: String!
  software_versions: [SoftwareVersion!]! @relationship(type:  "IN", direction: OUT)
  cve: CVE @relationship(type:  "REFERS_TO", direction: OUT)
}

type ResolvesTo @relationshipProperties {
  start: String
  end: String
}

type SoftwareOn @relationshipProperties {
  end: String
  start: String
  tag: [String]
}

type NetworkServiceOn @relationshipProperties {
  end: String
  start: String
  tag: [String]
}