openapi: 3.0.3
info:
  title: "ISIM"
  version: 0.1.0
paths:
  /assets:
    post:
      tags:
        - Assets
      description: Upload asset information to ISIM
      operationId: store_assets
      requestBody:
        content:
          application/json:
            schema:
              $ref: './pydantic_schemas.json#/components/schemas/AssetsPostDTO'
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "422":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /asset_info:
    get:
      tags:
        - Assets
      description: Get information about IP address
      operationId: ip_asset_info
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
        - name: ip
          in: query
          schema:
            type: string
            format: ip
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/AssetInfoResponseDTO'
  /easm:
    post:
      tags:
        - Assets
      description: Upload external attack surface management data to ISIM
      operationId: store_easm
      requestBody:
        content:
          application/json:
            schema:
              $ref: './pydantic_schemas.json#/components/schemas/EasmPostDTO'
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "422":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /missions:
    get:
      tags:
        - Missions
      description: Return information about stored missions
      operationId: get_missions
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/MissionInfoResponseDTO'

    post:
      tags:
        - Missions
      description: Upload mission information to ISIM
      operationId: store_missions
      requestBody:
        content:
          application/json:
            schema:
              $ref: './pydantic_schemas.json#/components/schemas/MissionPostDTO'
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "422":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /ip_assets:
    get:
      tags:
        - Assets
      description: Return IP assets and related entities
      operationId: get_ip_assets
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/IpAssetsResponseDTO'
  /subnets:
    get:
      tags:
        - Assets
      description: Return subnets and related entities
      operationId: get_subnets
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/SubnetsResponseDTO'
  /devices:
    get:
      tags:
        - Assets
      description: Return devices and related entities
      operationId: get_devices
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/DevicesResponseDTO'
  /org_units:
    get:
      tags:
        - Assets
      description: Return organization units and related entities
      operationId: get_org_units
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/OrganizationUnitsResponseDTO'
  /applications:
    get:
      tags:
        - Assets
      description: Return applications and related entities
      operationId: get_applications
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/ApplicationsResponseDTO'
  /cves:
    get:
      tags:
        - CVEs
      description: Return all CVEs
      operationId: get_cves
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/CveSummaryResponseDTO'
  /cve/{cve_id}:
    get:
      tags:
        - CVEs
      description: Return a CVE by ID
      operationId: get_cve
      parameters:
        - name: cve_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/CveNodeResponseDTO'
        "422":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /ip_cves/{ip}:
    get:
      tags:
        - CVEs
      description: Return CVEs for a given IP
      operationId: get_ip_cves
      parameters:
        - name: ip
          in: path
          required: true
          schema:
            type: string
            format: ip
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/CveNodeResponseDTO'
        "422":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /traceroute:
    post:
      tags:
        - Topology
      description: Upload traceroute data to build topology
      operationId: traceroute
      requestBody:
        content:
          application/json:
            schema:
              $ref: './pydantic_schemas.json#/components/schemas/TraceroutePostDTO'
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "422":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /betweenness_centrality:
    post:
      tags:
        - Topology
      description: Compute betweenness centrality for topology
      operationId: betweenness_centrality
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /degree_centrality:
    post:
      tags:
        - Topology
      description: Compute degree centrality for topology
      operationId: degree_centrality
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /store_criticality:
    post:
      tags:
        - Criticality
      description: Store mission criticality data
      operationId: store_criticality
      requestBody:
        content:
          application/json:
            schema:
              $ref: './pydantic_schemas.json#/components/schemas/StoreCriticalityPostDTO'
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "422":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /combine_criticality:
    post:
      tags:
        - Criticality
      description: Combine criticality values
      operationId: combine_criticality
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
  /ip_hierarchy_sync:
    post:
      tags:
        - Assets
      description: Synchronize IP hierarchy and subnets
      operationId: ip_hierarchy_sync
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/MessageResponseDTO'
  /slp_enrichment:
    post:
      tags:
        - Assets
      description: Store SLP enrichment data
      operationId: slp_enrichment
      requestBody:
        content:
          application/json:
            schema:
              $ref: './pydantic_schemas.json#/components/schemas/SlpEnrichmentPostDTO'
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "422":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: './pydantic_schemas.json#/components/schemas/PlainTextResponseDTO'
components:
  schemas: {}
tags:
  - name: Assets
    description: |-
      Assets API allows users to store and query asset information in ISIM component
  - name: Missions
    description: |-
      Missions API allows users to store and query mission data.
  - name: CVEs
    description: |-
      CVEs API allows users to query vulnerability and CVE information.
  - name: Topology
    description: |-
      Topology API allows users to upload and compute topology metrics.
  - name: Criticality
    description: |-
      Criticality API allows users to store and compute criticality metrics.
